### ISSUE TITLE
How to integrate?

### ISSUE THREAD

**Issue by ida** [collective/mailtoplone.base#3]
Hi @mrsavage, the 'recent' activity on this product makes me hope, it has gotten Plone-4-compat by now, right guess? I would love to test it, do you know, if there is a simple how-to or example-integration around? Best regards, Ida

**Comment by mrsavage** [comment]
Hi @ida the current status of mailtoplone is:

There is no Plone 4 compatible release of the various mailtoplone packages on pypi.

Some work was done on the core package:

https://github.com/collective/mailtoplone.base

It's installable,
you can create Inboxes and 
 the dropmail script works.

Normal Emails are fine, what doesn't work are emails with ical data (they should create Events, but they don't).

You can follow the Tutorial on plone.org:

http://plone.org/products/mailtoplone/documentation/tutorial/mailtoplone-integrate-emails-with-plone/introduction

for setting up mailtoplone (omit mailtoplone.policy(not needed) and mailtoplone.contentrules(not compatible) 

best regards 
mr savage

**Comment by ida** [comment]
@mrsavage, awesome, the master-branch works for me with Plone-4.3.3! 
I can also add an Inbox and execute the "dropemail"-script to magically fill the inbox from the command-line.
Now, if I want incoming mails automatically be added to the Plone-Inbox, I should integrate that script into the used email-server, right? I was hoping, if someone could share an example for that, preferably by integrating a third-party-provider, but I know it's kind of a luxurious wish :)
Thanks also for pointing to the docs on plone.org, I was actually not looking there (I usually look at pypi and then at the repo), if you like, I can include these docs into the package's docs-folder, e.g. as USAGE.txt. So cool this is still alive and thanks for your quick response!

**Comment by ida** [comment]
Could make it work in a testing-enviroment (receive mail of 3rd-party-mailaccount and push it to a Plone-site with a cron), hope to publish a how-to, soon. Thank you very much for writing this!
